version: "3.8"

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15
    container_name: nextjs-postgres
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 可选：初始化脚本
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  # 可选：Redis 缓存
  redis:
    image: redis:alpine
    container_name: nextjs-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  # 可选：pgAdmin 管理界面
  pgadmin:
    image: dpage/pgadmin4
    container_name: nextjs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ugreen.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
