import { Metadata } from "next";
import { LegalLayout } from "../components/legal/legal-layout";

export const metadata: Metadata = {
  title: "Terms of Service - Venus AI",
  description:
    "Read Venus AI's Terms of Service to understand the rules and regulations governing the use of our AI assistant platform.",
  openGraph: {
    title: "Terms of Service - Venus AI",
    description:
      "Read Venus AI's Terms of Service to understand the rules and regulations governing the use of our AI assistant platform.",
    type: "website",
  },
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="December 2, 2024">
      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using Venus AI ("Service"), you accept and agree to be
          bound by the terms and provision of this agreement. If you do not agree
          to these terms, please do not use our Service.
        </p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>
          Venus AI provides an AI-powered chat assistant platform that allows users
          to interact with advanced language models for various purposes including
          coding assistance, writing, research, and general conversation.
        </p>
      </section>

      <section>
        <h2>3. User Accounts</h2>
        <p>
          To access certain features of the Service, you may be required to create
          an account. You are responsible for:
        </p>
        <ul>
          <li>Maintaining the confidentiality of your account credentials</li>
          <li>All activities that occur under your account</li>
          <li>Notifying us immediately of any unauthorized use</li>
          <li>Providing accurate and complete information</li>
        </ul>
      </section>

      <section>
        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>
            Violate any applicable laws, regulations, or third-party rights
          </li>
          <li>
            Transmit any harmful, threatening, abusive, or harassing content
          </li>
          <li>
            Attempt to gain unauthorized access to our systems or networks
          </li>
          <li>Interfere with or disrupt the Service or servers</li>
          <li>
            Use the Service for any illegal or unauthorized purpose
          </li>
          <li>
            Generate content that infringes on intellectual property rights
          </li>
        </ul>
      </section>

      <section>
        <h2>5. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are
          owned by Venus AI and are protected by international copyright,
          trademark, patent, trade secret, and other intellectual property laws.
        </p>
        <p>
          You retain ownership of any content you input into the Service. By using
          the Service, you grant us a license to use, process, and display your
          input to provide and improve the Service.
        </p>
      </section>

      <section>
        <h2>6. AI-Generated Content</h2>
        <p>
          Content generated by our AI models is provided "as is" without any
          guarantees of accuracy, completeness, or reliability. You are responsible
          for verifying and validating any AI-generated content before use.
        </p>
      </section>

      <section>
        <h2>7. Billing and Payment</h2>
        <p>
          Certain features of the Service may require payment. By purchasing credits
          or subscribing to a plan, you agree to:
        </p>
        <ul>
          <li>Pay all applicable fees as described in our pricing</li>
          <li>Provide accurate billing information</li>
          <li>Understand that credits are non-refundable</li>
          <li>Accept that we may modify pricing with notice</li>
        </ul>
      </section>

      <section>
        <h2>8. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account at any time for
          violations of these terms or for any other reason. Upon termination, your
          right to use the Service will immediately cease.
        </p>
      </section>

      <section>
        <h2>9. Disclaimer of Warranties</h2>
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF
          ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
          WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT.
        </p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, VENUS AI SHALL NOT BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR
          ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY.
        </p>
      </section>

      <section>
        <h2>11. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. We will notify
          users of any material changes via email or through the Service. Your
          continued use of the Service after such modifications constitutes
          acceptance of the updated terms.
        </p>
      </section>

      <section>
        <h2>12. Contact Information</h2>
        <p>
          If you have any questions about these Terms of Service, please contact us
          at: support@venus-ai.com
        </p>
      </section>
    </LegalLayout>
  );
}

